// Prebuild: stamp the build id into the bundle (src/buildInfo.js, baked) AND publish
// public/version.json (fetched fresh at runtime). The app compares them: if the
// fetched version.json (always the latest deploy) differs from the baked BUILD_ID,
// the served bundle is stale → show the chip. Kills "hard-refresh and hope".
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';

let sha = 'dev';
try { sha = execSync('git rev-parse --short HEAD').toString().trim(); } catch { /* not a git checkout */ }
const builtAt = process.env.SOURCE_DATE_EPOCH
  ? new Date(Number(process.env.SOURCE_DATE_EPOCH) * 1000).toISOString()
  : new Date().toISOString();

writeFileSync('src/buildInfo.js', `// generated by scripts/gen-version.mjs at build\nexport const BUILD_ID = ${JSON.stringify(sha)};\nexport const BUILT_AT = ${JSON.stringify(builtAt)};\n`);
mkdirSync('public', { recursive: true });
writeFileSync('public/version.json', JSON.stringify({ build: sha, built_at: builtAt }) + '\n');
console.log(`[gen-version] BUILD_ID=${sha}`);
